spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5433/stackburguer
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver


# Isso aqui cria as tabelas no banco sozinho baseando-se no seu @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#MONGO

spring.data.mongodb.uri=mongodb://localhost:27017/stackburguer
